CREATE TABLE IF NOT EXISTS public.tbl_user_addresses (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  label varchar(60) default 'Home',
  recipient_name varchar(80),
  phone_number varchar(12),
  street text,
  district varchar(45),
  state varchar(45),
  landmark varchar(100),
  pin_code varchar(45),
  is_default boolean default false,
  inserted_at timestamptz default now(),
  updated_at timestamptz default now()
);

CREATE INDEX IF NOT EXISTS tbl_user_addresses_user_index
  ON public.tbl_user_addresses (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS tbl_user_addresses_one_default
  ON public.tbl_user_addresses (user_id)
  WHERE is_default = true;

INSERT INTO public.tbl_user_addresses (user_id, label, street, district, state, landmark, pin_code, is_default)
SELECT user_id, 'Home', street, district, state, landmark, pin_code, true
FROM public.tbl_user_details
WHERE street IS NOT NULL
  AND pin_code IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.tbl_user_addresses
    WHERE tbl_user_addresses.user_id = tbl_user_details.user_id
  );
