CREATE TABLE IF NOT EXISTS public.tbl_user_addresses (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  label varchar(60) default 'Home',
  recipient_name varchar(80),
  phone_number varchar(12),
  house_apartment text,
  street_name text,
  locality varchar(100),
  city varchar(80),
  street text,
  district varchar(45),
  state varchar(45),
  landmark varchar(100),
  pin_code varchar(45),
  is_default boolean default false,
  inserted_at timestamptz default now(),
  updated_at timestamptz default now()
);

ALTER TABLE public.tbl_user_addresses ADD COLUMN IF NOT EXISTS house_apartment text;
ALTER TABLE public.tbl_user_addresses ADD COLUMN IF NOT EXISTS street_name text;
ALTER TABLE public.tbl_user_addresses ADD COLUMN IF NOT EXISTS locality varchar(100);
ALTER TABLE public.tbl_user_addresses ADD COLUMN IF NOT EXISTS city varchar(80);

CREATE INDEX IF NOT EXISTS tbl_user_addresses_user_index
  ON public.tbl_user_addresses (user_id);

INSERT INTO public.tbl_user_addresses (user_id, label, street, district, state, landmark, pin_code, is_default)
SELECT user_id, 'Home', street, district, state, landmark, pin_code, true
FROM public.tbl_user_details
WHERE street IS NOT NULL
  AND pin_code IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.tbl_user_addresses
    WHERE tbl_user_addresses.user_id = tbl_user_details.user_id
  );

UPDATE public.tbl_user_addresses target
SET is_default = false
WHERE is_default = true
  AND id NOT IN (
    SELECT DISTINCT ON (user_id) id
    FROM public.tbl_user_addresses
    WHERE is_default = true
    ORDER BY user_id, updated_at DESC NULLS LAST, id DESC
  );

CREATE UNIQUE INDEX IF NOT EXISTS tbl_user_addresses_one_default
  ON public.tbl_user_addresses (user_id)
  WHERE is_default = true;
