services:
  - type: web
    name: jhatkabyte-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: ENV
        value: prod
      - key: CORS_ORIGINS
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_DB_URL
        sync: false
      - key: SUPABASE_DB_SSL
        value: "true"
      - key: SUPABASE_STORAGE_BUCKET
        value: jb-bucket
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
