const bcrypt = require("bcryptjs");
const config = require("../../config").get(process.env.ENV);
const {
  runMysqlQuery,
  runMysqlQueryWithParam,
  mysqlConnect,
  beginTransaction,
  commit,
  runTransectionQuery,
  rollback,
} = require("../../config/mysqlConfig");
const { generateRandomString } = require("../../utils/utilityFunctions");

const OUT_OF_SERVICE_MSG = "Out of service area definition";

const ADDRESS_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS public.tbl_user_addresses (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  label varchar(60) default 'Home',
  recipient_name varchar(80),
  phone_number varchar(12),
  street text,
  district varchar(45),
  state varchar(45),
  landmark varchar(100),
  pin_code varchar(45),
  is_default boolean default false,
  inserted_at timestamptz default now(),
  updated_at timestamptz default now()
)`;

let addressBookReady = false;

const ensureAddressBookTable = async () => {
  if (addressBookReady) return;
  await runMysqlQuery(ADDRESS_TABLE_SQL);
  await runMysqlQuery(`CREATE INDEX IF NOT EXISTS tbl_user_addresses_user_index ON public.tbl_user_addresses (user_id)`);
  await runMysqlQuery(`CREATE UNIQUE INDEX IF NOT EXISTS tbl_user_addresses_one_default ON public.tbl_user_addresses (user_id) WHERE is_default = true`);
  addressBookReady = true;
};

const getFranchiseForPincode = async (pincode) => {
  const normalizedPincode = `${pincode || ""}`.trim();
  if (!normalizedPincode) return null;
  const param = JSON.stringify([normalizedPincode]);
  const franchiseSql = `SELECT user_id FROM tbl_franchise_details WHERE JSON_CONTAINS(zip_codes, ?)`;
  const franchise = await runMysqlQueryWithParam(franchiseSql, [param]);
  return franchise.length ? franchise[0] : null;
};

const getCurrentUser = async (userId, roleId) => {
  try {
    if (Number(roleId) === 4) {
      console.log("userId = ", userId);
      await ensureAddressBookTable();
      const sql = `SELECT u.id, u.email, u.name, u.phone_number, u.status, d.street, d.district, d.state, d.landmark, d.pin_code FROM tbl_users u LEFT JOIN tbl_user_details d ON u.id=d.user_id WHERE u.role_id=4 AND u.id=?`;
      const check = await runMysqlQueryWithParam(sql, [userId]);
      if (check.length) {
        const addressList = await getUserAddressList(userId);
        return {
          status: true,
          msg: "Admin info fetched successfully",
          responseObj: { ...check[0], addressList: addressList.responseObj },
        };
      } else {
        return { status: false, msg: "Unable to get user info", responseObj: {} };
      }
    } else {
      return { status: false, msg: "User not authorized", responseObj: {} };
    }
  } catch (e) {
    return { status: false, msg: "Please try again", responseObj: {} };
  }
};

const getUserDistrict = async (pincode) => {
  try {
    const normalizedPincode = `${pincode || ""}`.trim();
    const franchise = await getFranchiseForPincode(normalizedPincode);
    if (!normalizedPincode || !franchise?.user_id) {
      return { status: false, msg: OUT_OF_SERVICE_MSG, responseObj: "" };
    }
    const sql = `SELECT district FROM mst_pin_codes WHERE pin_code=?`;
    const response = await runMysqlQueryWithParam(sql, [normalizedPincode]);
    if (response.length) {
      return {
        status: true,
        msg: "District fetched successfully",
        responseObj: response[0].district,
      };
    } else {
      return {
        status: false,
        msg: OUT_OF_SERVICE_MSG,
        responseObj: "",
      };
    }
  } catch (e) {
    return { status: false, msg: "Please try again", responseObj: {} };
  }
};

const getDistrictList = async () => {
  try {
    const sql = `SELECT DISTINCT(district) FROM mst_pin_codes order by district asc`;
    const response = await runMysqlQuery(sql);
    return {
      status: true,
      msg: "District fetched successfully",
      responseObj: response,
    };
  } catch (e) {
    return { status: false, msg: "Could not fetch district list. Please try again", responseObj: [] };
  }
};

const addUserAddress = async (street, state, district, pincode, landmark, user_id) => {
  console.log("user_id = ", user_id);
  try {
    await ensureAddressBookTable();
    const normalizedPincode = `${pincode || ""}`.trim();
    const normalizedDistrict = `${district || ""}`.trim();
    const normalizedLabel = "Home";
    const franchise = await getFranchiseForPincode(normalizedPincode);
    if (!normalizedPincode || !franchise?.user_id) {
      return { status: false, msg: OUT_OF_SERVICE_MSG, responseObj: [] };
    }
    const sql = `select district from mst_pin_codes where pin_code=?`;
    const check = await runMysqlQueryWithParam(sql, [normalizedPincode]);
    if (!check.length) return { status: false, msg: OUT_OF_SERVICE_MSG, responseObj: [] };
    if (`${check[0].district || ""}`.trim().toLowerCase() !== normalizedDistrict.toLowerCase()) {
      return { status: false, msg: "District and pin code does not match", responseObj: [] };
    }
    const addressList = await runMysqlQueryWithParam("SELECT id FROM tbl_user_addresses WHERE user_id=? ORDER BY is_default DESC, id ASC", [user_id]);
    const addressId = addressList?.[0]?.id;
    if (addressId) {
      await runMysqlQueryWithParam("UPDATE tbl_user_addresses SET is_default=false WHERE user_id=?", [user_id]);
      await runMysqlQueryWithParam(
        "UPDATE tbl_user_addresses SET label=?, street=?, state=?, district=?, pin_code=?, landmark=?, is_default=true, updated_at=now() WHERE id=? AND user_id=?",
        [normalizedLabel, street, state, normalizedDistrict, normalizedPincode, landmark, addressId, user_id]
      );
    } else {
      await runMysqlQueryWithParam(
        "INSERT INTO tbl_user_addresses (user_id, label, street, state, district, pin_code, landmark, is_default) VALUES (?,?,?,?,?,?,?,true)",
        [user_id, normalizedLabel, street, state, normalizedDistrict, normalizedPincode, landmark]
      );
    }
    const userCheck = await runMysqlQueryWithParam("select id from tbl_user_details where user_id=?", [user_id]);
    if (userCheck.length) {
      const updateSql = `update tbl_user_details set street=?, state=?, district=?, pin_code=?, landmark=? where user_id=?`;
      await runMysqlQueryWithParam(updateSql, [street, state, normalizedDistrict, normalizedPincode, landmark, user_id]);
    } else {
      const addSql = `insert into tbl_user_details (user_id, street, state, district, pin_code, landmark) values (?,?,?,?,?,?)`;
      await runMysqlQueryWithParam(addSql, [user_id, street, state, normalizedDistrict, normalizedPincode, landmark]);
    }
    return {
      status: true,
      msg: "Address updated successfully",
      responseObj: { street, state, district: normalizedDistrict, pin_code: normalizedPincode, landmark },
    };
  } catch (e) {
    console.log(e);
    return { status: false, msg: "Could not update address. Please try again", responseObj: [] };
  }
};

const validateAddressData = async (data) => {
  const normalizedPincode = `${data?.pincode || data?.pin_code || ""}`.trim();
  const normalizedDistrict = `${data?.district || ""}`.trim();
  const franchise = await getFranchiseForPincode(normalizedPincode);
  if (!normalizedPincode || !franchise?.user_id) {
    return { status: false, msg: OUT_OF_SERVICE_MSG };
  }
  const check = await runMysqlQueryWithParam("SELECT district FROM mst_pin_codes WHERE pin_code=?", [normalizedPincode]);
  if (!check.length) return { status: false, msg: OUT_OF_SERVICE_MSG };
  if (`${check[0].district || ""}`.trim().toLowerCase() !== normalizedDistrict.toLowerCase()) {
    return { status: false, msg: "District and pin code does not match" };
  }
  return { status: true, pincode: normalizedPincode, district: normalizedDistrict };
};

const getUserAddressList = async (user_id) => {
  try {
    await ensureAddressBookTable();
    const list = await runMysqlQueryWithParam(
      `SELECT id, label, recipient_name, phone_number, street, district, state, landmark, pin_code, is_default
       FROM tbl_user_addresses WHERE user_id=? ORDER BY is_default DESC, id DESC`,
      [user_id]
    );
    if (!list.length) {
      const legacy = await runMysqlQueryWithParam(
        "SELECT street, district, state, landmark, pin_code FROM tbl_user_details WHERE user_id=? AND street IS NOT NULL AND pin_code IS NOT NULL",
        [user_id]
      );
      if (legacy.length) {
        await runMysqlQueryWithParam(
          "INSERT INTO tbl_user_addresses (user_id, label, street, district, state, landmark, pin_code, is_default) VALUES (?,?,?,?,?,?,?,true)",
          [user_id, "Home", legacy[0].street, legacy[0].district, legacy[0].state, legacy[0].landmark, legacy[0].pin_code]
        );
        return getUserAddressList(user_id);
      }
    }
    return { status: true, msg: "Address list fetched successfully", responseObj: list };
  } catch (e) {
    console.log(e);
    return { status: false, msg: "Could not fetch address book. Please try again", responseObj: [] };
  }
};

const saveUserAddress = async (data, user_id) => {
  try {
    await ensureAddressBookTable();
    const validation = await validateAddressData(data);
    if (!validation.status) return { status: false, msg: validation.msg, responseObj: [] };

    const label = `${data.label || "Home"}`.trim() || "Home";
    const recipientName = `${data.recipient_name || data.recipientName || ""}`.trim() || null;
    const phoneNumber = `${data.phone_number || data.phoneNumber || ""}`.trim() || null;
    const street = `${data.street || ""}`.trim();
    const state = `${data.state || "West Bengal"}`.trim();
    const landmark = `${data.landmark || ""}`.trim();
    const addressId = Number(data.id || 0);
    const existing = await runMysqlQueryWithParam("SELECT id FROM tbl_user_addresses WHERE user_id=?", [user_id]);
    const shouldBeDefault = data.isDefault === true || data.is_default === true || !existing.length;

    if (!street) return { status: false, msg: "Please enter your street", responseObj: [] };

    if (shouldBeDefault) {
      await runMysqlQueryWithParam("UPDATE tbl_user_addresses SET is_default=false WHERE user_id=?", [user_id]);
    }

    let savedId = addressId;
    if (addressId) {
      const update = await runMysqlQueryWithParam(
        `UPDATE tbl_user_addresses
         SET label=?, recipient_name=?, phone_number=?, street=?, state=?, district=?, pin_code=?, landmark=?, is_default=?, updated_at=now()
         WHERE id=? AND user_id=?`,
        [label, recipientName, phoneNumber, street, state, validation.district, validation.pincode, landmark, shouldBeDefault, addressId, user_id]
      );
      if (!update.affectedRows) return { status: false, msg: "Address not found", responseObj: [] };
    } else {
      const insert = await runMysqlQueryWithParam(
        `INSERT INTO tbl_user_addresses
         (user_id, label, recipient_name, phone_number, street, state, district, pin_code, landmark, is_default)
         VALUES (?,?,?,?,?,?,?,?,?,?)`,
        [user_id, label, recipientName, phoneNumber, street, state, validation.district, validation.pincode, landmark, shouldBeDefault]
      );
      savedId = insert.insertId;
    }

    if (shouldBeDefault) {
      await syncDefaultAddressToUserDetails(user_id);
    }

    const addressList = await getUserAddressList(user_id);
    const savedAddress = addressList.responseObj.find((item) => Number(item.id) === Number(savedId)) || addressList.responseObj[0];
    return { status: true, msg: addressId ? "Address updated successfully" : "Address saved successfully", responseObj: { savedAddress, addressList: addressList.responseObj } };
  } catch (e) {
    console.log(e);
    return { status: false, msg: "Could not save address. Please try again", responseObj: [] };
  }
};

const syncDefaultAddressToUserDetails = async (user_id) => {
  const defaults = await runMysqlQueryWithParam("SELECT street, district, state, landmark, pin_code FROM tbl_user_addresses WHERE user_id=? AND is_default=true LIMIT 1", [user_id]);
  if (!defaults.length) return;
  const item = defaults[0];
  const userCheck = await runMysqlQueryWithParam("select id from tbl_user_details where user_id=?", [user_id]);
  if (userCheck.length) {
    await runMysqlQueryWithParam("update tbl_user_details set street=?, state=?, district=?, pin_code=?, landmark=? where user_id=?", [item.street, item.state, item.district, item.pin_code, item.landmark, user_id]);
  } else {
    await runMysqlQueryWithParam("insert into tbl_user_details (user_id, street, state, district, pin_code, landmark) values (?,?,?,?,?,?)", [user_id, item.street, item.state, item.district, item.pin_code, item.landmark]);
  }
};

const setDefaultUserAddress = async (addressId, user_id) => {
  try {
    await ensureAddressBookTable();
    const check = await runMysqlQueryWithParam("SELECT id FROM tbl_user_addresses WHERE id=? AND user_id=?", [addressId, user_id]);
    if (!check.length) return { status: false, msg: "Address not found", responseObj: [] };
    await runMysqlQueryWithParam("UPDATE tbl_user_addresses SET is_default=false WHERE user_id=?", [user_id]);
    await runMysqlQueryWithParam("UPDATE tbl_user_addresses SET is_default=true, updated_at=now() WHERE id=? AND user_id=?", [addressId, user_id]);
    await syncDefaultAddressToUserDetails(user_id);
    const addressList = await getUserAddressList(user_id);
    return { status: true, msg: "Default address updated successfully", responseObj: addressList.responseObj };
  } catch (e) {
    console.log(e);
    return { status: false, msg: "Could not update default address. Please try again", responseObj: [] };
  }
};

const deleteUserAddress = async (addressId, user_id) => {
  try {
    await ensureAddressBookTable();
    const check = await runMysqlQueryWithParam("SELECT id, is_default FROM tbl_user_addresses WHERE id=? AND user_id=?", [addressId, user_id]);
    if (!check.length) return { status: false, msg: "Address not found", responseObj: [] };
    if (check[0].is_default) return { status: false, msg: "Default address cannot be deleted. Set another default address first.", responseObj: [] };
    await runMysqlQueryWithParam("DELETE FROM tbl_user_addresses WHERE id=? AND user_id=?", [addressId, user_id]);
    const addressList = await getUserAddressList(user_id);
    return { status: true, msg: "Address deleted successfully", responseObj: addressList.responseObj };
  } catch (e) {
    console.log(e);
    return { status: false, msg: "Could not delete address. Please try again", responseObj: [] };
  }
};

const updateUserAccount = async (formData, email) => {
  try {
    const sql = `select id from tbl_users where email=?`;
    const check = await runMysqlQueryWithParam(sql, [email.trim()]);
    if (check.length) {
      let updateSql = `update tbl_users set name=? where id=?`;
      if (formData.password) {
        updateSql = `update tbl_users set name=?, password=? where id=?`;
        const hashedPassword = bcrypt.hashSync(formData.password, config.saltRounds);
        await runMysqlQueryWithParam(updateSql, [`${formData.firstName} ${formData.lastName}`, hashedPassword, check[0].id]);
      } else {
        await runMysqlQueryWithParam(updateSql, [`${formData.firstName} ${formData.lastName}`, check[0].id]);
      }
      return { status: true, msg: "Account information updated successfully", responseObj: [] };
    } else {
      return { status: false, msg: "User not permitted to update account information", responseObj: [] };
    }
  } catch (e) {
    console.log(e);
    return { status: false, msg: "Could not update user information. Please try again", responseObj: [] };
  }
};

module.exports = {
  getCurrentUser,
  getUserDistrict,
  getDistrictList,
  addUserAddress,
  getUserAddressList,
  saveUserAddress,
  setDefaultUserAddress,
  deleteUserAddress,
  updateUserAccount,
};
