-- Run this in the Supabase SQL editor for the project backing this app.
-- The app expects these tables in the public schema.

create table if not exists public.tbl_users (
  id bigint generated by default as identity primary key,
  role_id integer not null,
  email varchar(60) not null,
  password varchar(100) not null,
  secret_code varchar(100),
  name varchar(50),
  phone_number varchar(12),
  status smallint default 1,
  added_by bigint,
  inserted_at timestamptz default now(),
  modified_at timestamptz default now()
);

create unique index if not exists tbl_users_email_role_unique
  on public.tbl_users (email, role_id);

create table if not exists public.tbl_user_details (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  is_confirmed smallint default 1,
  login_type smallint default 1,
  street text,
  district varchar(45),
  state varchar(45),
  landmark varchar(100),
  pin_code varchar(45)
);

create unique index if not exists tbl_user_details_user_unique
  on public.tbl_user_details (user_id);

create table if not exists public.tbl_category (
  id bigint generated by default as identity primary key,
  name varchar(50) not null,
  status smallint default 1,
  inserted_at timestamptz default now(),
  modified_at timestamptz default now()
);

create unique index if not exists tbl_category_name_unique
  on public.tbl_category (name);

create table if not exists public.tbl_products (
  id bigint generated by default as identity primary key,
  category_id bigint not null,
  name varchar(50) not null,
  description text not null,
  images text not null,
  status smallint default 1,
  inserted_at timestamptz default now(),
  modified_at timestamptz default now()
);

create table if not exists public.tbl_product_price (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  role_id integer not null,
  user_id bigint not null,
  category_id bigint,
  added_by bigint not null,
  quantity_wise_price text,
  is_available smallint default 0,
  delevery_days text,
  inserted_at timestamptz default now(),
  modified_at timestamptz default now()
);

create unique index if not exists tbl_product_price_product_user_unique
  on public.tbl_product_price (product_id, user_id);

create table if not exists public.tbl_franchise_details (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  franchise_name varchar(60),
  state varchar(60) not null,
  district varchar(60),
  zip_codes jsonb default '[]'::jsonb
);

create unique index if not exists tbl_franchise_details_user_unique
  on public.tbl_franchise_details (user_id);

create table if not exists public.tbl_cart (
  id bigint generated by default as identity primary key,
  "cartId" varchar(50) not null,
  "userId" bigint,
  "productId" bigint,
  "franchiseId" bigint,
  price double precision,
  quantity integer,
  unit varchar(5),
  count integer,
  "shippingCost" double precision
);

create index if not exists tbl_cart_cart_id_index on public.tbl_cart ("cartId");
create index if not exists tbl_cart_user_id_index on public.tbl_cart ("userId");

create table if not exists public.tbl_orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  franchise_id bigint not null,
  delevery_boy_id bigint,
  ref_no varchar(45),
  total_price double precision not null,
  status smallint default 1,
  phone_number varchar(45),
  shipping_address text,
  billing_address text,
  name varchar(50),
  state varchar(45),
  district varchar(45),
  additional_notes text,
  pin_code varchar(45),
  delivery_date text,
  inserted_at timestamptz default now(),
  updated_at timestamptz default now(),
  landmark text,
  shipping_cost double precision default 0
);

create unique index if not exists tbl_orders_ref_no_unique
  on public.tbl_orders (ref_no);

create table if not exists public.tbl_order_details (
  id bigint generated by default as identity primary key,
  order_id bigint not null,
  product_id bigint not null,
  quantity varchar(45) not null,
  shipping_cost double precision default 0,
  price double precision,
  unit varchar(45),
  count integer,
  delivery_date varchar(45),
  delivery_status smallint default 1,
  delivery_boy_id bigint
);

create table if not exists public.tbl_shipping_cost (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  pin_code varchar(45) not null,
  shipping_cost double precision default 0
);

create unique index if not exists tbl_shipping_cost_user_pin_unique
  on public.tbl_shipping_cost (user_id, pin_code);

create table if not exists public.mst_pin_codes (
  id bigint generated by default as identity primary key,
  pin_code varchar(1024),
  area varchar(1024),
  district varchar(1024)
);

create index if not exists mst_pin_codes_pin_code_index
  on public.mst_pin_codes (pin_code);

create table if not exists public.tbl_product_review (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  user_id bigint not null,
  message text,
  stars integer,
  status smallint default 1,
  inserted_at timestamptz default now(),
  modified_at timestamptz default now()
);

create table if not exists public.tbl_franchise_requests (
  id bigint generated by default as identity primary key,
  name varchar(50),
  email varchar(60),
  phone_number varchar(12),
  state varchar(60),
  district varchar(60),
  address text,
  status smallint default 1,
  inserted_at timestamptz default now(),
  modified_at timestamptz default now()
);

create table if not exists public.tbl_delevery_boy_details (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  state varchar(60),
  district varchar(60),
  address text,
  inserted_at timestamptz default now(),
  modified_at timestamptz default now()
);
